services:
  - type: web
    name: heart-attack-risk-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
    healthCheckPath: /
    autoDeploy: true
